name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag luminance/mc-webhook:latest
    - name: Publish the Image to Docker Hub
      run: |
          docker login -u luminance -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push luminance/mc-webhook:latest
